<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<AssemblyTitle>VSCA Subscriber Manager</AssemblyTitle>
		<AssemblyName>VSCA Subscriber Manager</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CsvHelper" Version="33.1.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SnowmobileLibrary\SnowmobileLibrary.csproj" />
	</ItemGroup>

</Project>