// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SnowmobileLibrary.Data;

#nullable disable

namespace SnowmobileLibrary.Migrations
{
    [DbContext(typeof(SnowmobileContext))]
    [Migration("20260212004352_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SnowmobileLibrary.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VSCA")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("VSCA");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("SnowmobileLibrary.Models.Email", b =>
                {
                    b.Property<int>("EmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailId"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("VSCA")
                        .HasColumnType("int");

                    b.HasKey("EmailId");

                    b.HasIndex("VSCA");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("SnowmobileLibrary.Models.Subscriber", b =>
                {
                    b.Property<int>("VSCA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VSCA"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Commercial")
                        .HasColumnType("bit");

                    b.Property<bool>("Contest")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("DateJoined")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ManualMail")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("VSCA");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("SnowmobileLibrary.Models.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<DateOnly>("DateRenewed")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpDate")
                        .HasColumnType("date");

                    b.Property<int>("IssuesRemaining")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VSCA")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("VSCA");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("SnowmobileLibrary.Models.Address", b =>
                {
                    b.HasOne("SnowmobileLibrary.Models.Subscriber", "Subscriber")
                        .WithMany()
                        .HasForeignKey("VSCA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("SnowmobileLibrary.Models.Email", b =>
                {
                    b.HasOne("SnowmobileLibrary.Models.Subscriber", "Subscriber")
                        .WithMany()
                        .HasForeignKey("VSCA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("SnowmobileLibrary.Models.Subscription", b =>
                {
                    b.HasOne("SnowmobileLibrary.Models.Subscriber", "Subscriber")
                        .WithMany()
                        .HasForeignKey("VSCA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscriber");
                });
#pragma warning restore 612, 618
        }
    }
}
